version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  serviceregistry:
    container_name: serviceregistry
    image: svetlint/serviceregistry:latest
    depends_on:
      - mysql
    volumes:
      - ./properties/serviceregistry.properties:/serviceregistry/application.properties
    ports:
      - 8443:8443

  authorization:
    container_name: authorization
    image: svetlint/authorization:latest
    depends_on:
      - mysql
    volumes:
      - ./properties/authorization.properties:/authorization/application.properties
    ports:
      - 8445:8445

  orchestrator:
    container_name: orchestrator
    image: svetlint/orchestrator:latest
    depends_on:
      - mysql
    volumes:
      - ./properties/orchestrator.properties:/orchestrator/application.properties
    ports:
      - 8441:8441

  # eventhandler:
  #   container_name: eventhandler
  #   image: svetlint/eventhandler:latest
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./properties/eventhandler.properties:/eventhandler/application.properties
  #   ports:
  #     - 8455:8455
  
  # gatekeeper:
  #   container_name: gatekeeper
  #   image: svetlint/gatekeeper:latest
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./properties/gatekeeper.properties:/gatekeeper/application.properties
  #   ports:
  #     - 8449:8449

  # gateway:
  #   container_name: gateway
  #   image: svetlint/gateway:latest
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./properties/gateway.properties:/gateway/application.properties
  #   ports:
  #     - 8453:8453

  # certificateauthority:
  #   container_name: certificateauthority
  #   image: svetlint/certificateauthority:latest
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./properties/certificateauthority.properties:/certificateauthority/application.properties
  #   ports:
  #     - 8448:8448 

volumes:
  mysql:
    external: true  
